/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodsRouteImport } from './routes/pods'
import { Route as CostingIdRouteImport } from './routes/costing.$id'
import { Route as PodsIndexRouteImport } from './routes/pods.index'
import { Route as PodsIdRouteImport } from './routes/pods.$id'
import { Route as PodsNewRouteImport } from './routes/pods.new'
import { Route as ConfigPodIdArticleIdRouteImport } from './routes/config.$podId.$articleId'
import { Route as ProductPodIdArticleIdRouteImport } from './routes/product.$podId.$articleId'
import { Route as QuotationPodIdArticleIdRouteImport } from './routes/quotation.$podId.$articleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodsRoute = PodsRouteImport.update({
  id: '/pods',
  path: '/pods',
  getParentRoute: () => rootRouteImport,
} as any)
const CostingIdRoute = CostingIdRouteImport.update({
  id: '/costing/$id',
  path: '/costing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PodsIndexRoute = PodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodsRoute,
} as any)
const PodsIdRoute = PodsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PodsRoute,
} as any)
const PodsNewRoute = PodsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PodsRoute,
} as any)
const ConfigPodIdArticleIdRoute = ConfigPodIdArticleIdRouteImport.update({
  id: '/config/$podId/$articleId',
  path: '/config/$podId/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPodIdArticleIdRoute = ProductPodIdArticleIdRouteImport.update({
  id: '/product/$podId/$articleId',
  path: '/product/$podId/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationPodIdArticleIdRoute = QuotationPodIdArticleIdRouteImport.update({
  id: '/quotation/$podId/$articleId',
  path: '/quotation/$podId/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pods': typeof PodsRouteWithChildren
  '/costing/$id': typeof CostingIdRoute
  '/pods/$id': typeof PodsIdRoute
  '/pods/new': typeof PodsNewRoute
  '/pods/': typeof PodsIndexRoute
  '/config/$podId/$articleId': typeof ConfigPodIdArticleIdRoute
  '/product/$podId/$articleId': typeof ProductPodIdArticleIdRoute
  '/quotation/$podId/$articleId': typeof QuotationPodIdArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/costing/$id': typeof CostingIdRoute
  '/pods/$id': typeof PodsIdRoute
  '/pods/new': typeof PodsNewRoute
  '/pods': typeof PodsIndexRoute
  '/config/$podId/$articleId': typeof ConfigPodIdArticleIdRoute
  '/product/$podId/$articleId': typeof ProductPodIdArticleIdRoute
  '/quotation/$podId/$articleId': typeof QuotationPodIdArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pods': typeof PodsRouteWithChildren
  '/costing/$id': typeof CostingIdRoute
  '/pods/$id': typeof PodsIdRoute
  '/pods/new': typeof PodsNewRoute
  '/pods/': typeof PodsIndexRoute
  '/config/$podId/$articleId': typeof ConfigPodIdArticleIdRoute
  '/product/$podId/$articleId': typeof ProductPodIdArticleIdRoute
  '/quotation/$podId/$articleId': typeof QuotationPodIdArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pods'
    | '/costing/$id'
    | '/pods/$id'
    | '/pods/new'
    | '/pods/'
    | '/config/$podId/$articleId'
    | '/product/$podId/$articleId'
    | '/quotation/$podId/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/costing/$id'
    | '/pods/$id'
    | '/pods/new'
    | '/pods'
    | '/config/$podId/$articleId'
    | '/product/$podId/$articleId'
    | '/quotation/$podId/$articleId'
  id:
    | '__root__'
    | '/'
    | '/pods'
    | '/costing/$id'
    | '/pods/$id'
    | '/pods/new'
    | '/pods/'
    | '/config/$podId/$articleId'
    | '/product/$podId/$articleId'
    | '/quotation/$podId/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodsRoute: typeof PodsRouteWithChildren
  CostingIdRoute: typeof CostingIdRoute
  ConfigPodIdArticleIdRoute: typeof ConfigPodIdArticleIdRoute
  ProductPodIdArticleIdRoute: typeof ProductPodIdArticleIdRoute
  QuotationPodIdArticleIdRoute: typeof QuotationPodIdArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pods': {
      id: '/pods'
      path: '/pods'
      fullPath: '/pods'
      preLoaderRoute: typeof PodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costing/$id': {
      id: '/costing/$id'
      path: '/costing/$id'
      fullPath: '/costing/$id'
      preLoaderRoute: typeof CostingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pods/': {
      id: '/pods/'
      path: '/'
      fullPath: '/pods/'
      preLoaderRoute: typeof PodsIndexRouteImport
      parentRoute: typeof PodsRoute
    }
    '/pods/$id': {
      id: '/pods/$id'
      path: '/$id'
      fullPath: '/pods/$id'
      preLoaderRoute: typeof PodsIdRouteImport
      parentRoute: typeof PodsRoute
    }
    '/pods/new': {
      id: '/pods/new'
      path: '/new'
      fullPath: '/pods/new'
      preLoaderRoute: typeof PodsNewRouteImport
      parentRoute: typeof PodsRoute
    }
    '/config/$podId/$articleId': {
      id: '/config/$podId/$articleId'
      path: '/config/$podId/$articleId'
      fullPath: '/config/$podId/$articleId'
      preLoaderRoute: typeof ConfigPodIdArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$podId/$articleId': {
      id: '/product/$podId/$articleId'
      path: '/product/$podId/$articleId'
      fullPath: '/product/$podId/$articleId'
      preLoaderRoute: typeof ProductPodIdArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation/$podId/$articleId': {
      id: '/quotation/$podId/$articleId'
      path: '/quotation/$podId/$articleId'
      fullPath: '/quotation/$podId/$articleId'
      preLoaderRoute: typeof QuotationPodIdArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PodsRouteChildren {
  PodsIdRoute: typeof PodsIdRoute
  PodsNewRoute: typeof PodsNewRoute
  PodsIndexRoute: typeof PodsIndexRoute
}

const PodsRouteChildren: PodsRouteChildren = {
  PodsIdRoute: PodsIdRoute,
  PodsNewRoute: PodsNewRoute,
  PodsIndexRoute: PodsIndexRoute,
}

const PodsRouteWithChildren = PodsRoute._addFileChildren(PodsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodsRoute: PodsRouteWithChildren,
  CostingIdRoute: CostingIdRoute,
  ConfigPodIdArticleIdRoute: ConfigPodIdArticleIdRoute,
  ProductPodIdArticleIdRoute: ProductPodIdArticleIdRoute,
  QuotationPodIdArticleIdRoute: QuotationPodIdArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
